"""item model added with relationship

Revision ID: 5dbcf3db4905
Revises: c122517d2a6e
Create Date: 2024-01-30 12:19:48.860384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dbcf3db4905'
down_revision = 'c122517d2a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_items_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('img_url')

    op.drop_table('items')
    # ### end Alembic commands ###
