"""change owner_id to user_id in store table

Revision ID: eb7a3f543df4
Revises: e5cee08079de
Create Date: 2024-01-28 14:21:08.174163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7a3f543df4'
down_revision = 'e5cee08079de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_stores_owner_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stores_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_stores_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_stores_owner_id_users', 'users', ['owner_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
